1.  Manejo de Excepciones. Es un mecanismo que sirve para
    interrumpir el flujo normal del programa y continuar en 
    algun contexto rodeado o bloque de codigo que majejara
    dicha interrupcion.

2.  Conceptos claves:
    i)  Levantar una excepción
    ii) Manejo de una Excepcion
    iii)Excepción no controlada
    iv) Objetos de Excepción

3.  Las excepciones provenientes de errores del programador:
        * IntentationError
        * SyntaxError
        * NameError
    Casi nunca deberian ser cachadas.

4.  Para que cuando un bloque de codigo contenga una linea vacia,
    sin codigo, no levante una excepcion se usa la palabra pass 
    en dicho bloque, en dicha linea, que es como un no-op o 
    no operation line, una linea sin operacion.

5.  El formato de una excepcion es el siguiente:
    try:
        bloque
        de
        codigo
    except (TipoError1[,TipoError2, . . . ,TipoErrorN]) as e:
        lo que se tiene
        que hacer para
        manejar el error
    except OtroError:
        tambien se puede usar
        un except por cada Tipo
        de Error. O un renglon 
        por cada except
    
6.  Para elevar una excepcion y replicarla hacia arriba en las 
    llamadas se utiliza la palabra clave "raise"

7.  No es para nada recomendable degresar codigos numericos cuando ocurre 
    alguna excepcion. Es mejor usar raise para que levante la excepcion 
    y manejarla en el nivel siguiente superior.

8.  Existe un formato para mostrar el contenido de una excepcion cuando
    ocurre, a continuacion se muestra

9.  Tipos de Excepciones mas comunes:
    * IndexError    Cuando se hace referencia a un indice que sobre pasa el indice mayor de la lista
    * ValueError    Cuando se introduce un objeto permitido pero su contenido es inapropiado. Ejemplo:
                    >>> int("hola")
    * KeyError      Cuando la busqueda dentro de un mapa falla. Ejemplo:
                    >>> codes = dict(fdx=73, li=78, yol=78)
                    >>> codes
                    {'fdx': 73, 'li': 78, 'yol': 78}
                    >>> codes['fdx']
                    73
                    >>> codes['vale']
                    Traceback (most recent call last):
                    File "<stdin>", line 1, in <module>
                    KeyError: 'vale'
